#!/bin/bash
# Command line argument for class folder
class=$1
lec_num=$2
mainpath=~/Documents/semester_4/$class/Notes
lecpath=$mainpath/Lecture

# Copy template lecture file
nvim $lecpath/$lec_num.tex
