background = "#282828"
color = "#ffffff"
separator = "#9a8a62"
tag_fg = "#d79921"
tag_bg = "#282828"
tag_focused_fg = "#1d2021"
tag_focused_bg = "#689d68"
tag_urgent_fg = "#282828"
tag_urgent_bg = "#cc241d"
tag_inactive_fg = "#d79921"
tag_inactive_bg = "#282828"
font = "Source Code Pro 10"
height = 20
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
separator_width = 0
tags_r = 0
tags_padding = 10
blocks_r = 0
blocks_overlap = 0
command = "i3status-rs"
position = "top"
hide_inactive_tags = true
invert_touchpad_scrolling = true
show_layout_name = false
