#!/usr/bin/env bash

# give_ap - create_ap script. Creates access point.

name=''
pass=''

if [ "$1" != "" ] && [ "$2" != "" ]; then
    echo "Network name: $1"
    echo "Network password: $2"
    rm /tmp/create_ap.all.lock
    create_ap --daemon --no-virt wlp2s0 enp0s20f0u4 $1 $2
else
    echo "Network name and password should be specified."
fi
