#! /bin/sh

sxhkd &
#nitrogen --restore &

#hsetroot -solid white -full ~/Pictures/potential_wallpapers/light.jpg
hsetroot -solid white -fill ~/Pictures/potential_wallpapers/dark.jpg

#picom -bcf -o 0.38 -t 0 -l 0 -r 8 -D 8
picom -bcf --config ~/.config/picom/picom.conf
$HOME/.config/polybar/scripts/launch-polybar &

#start_jack.sh
# redshift &
setxkbmap -layout "us,ru" -variant ,phonetic_custom -option "grp:ctrl_alt_toggle,lv3:ralt_switch" &
#nm-applet &
#mate-power-manager &
xsetroot -cursor_name left_ptr &
#mpd &
dunst &
#check_audio_card.sh
eww daemon


bspc monitor -d 1 2 3 4 5 6 7 8
#bspc monitor HDMI2 -d 1 2 3 4 5 6 7 8

bspc config border_width        1
bspc config window_gap          12
bspc config border_radius		11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#############

# picom --config /dev/null -r 15 -l -15 -t -15 -o .7 -c

# polybar main &
# polybar external &
# nm-applet &
# dunst &
# xfce4-power-manager &
#xset r rate 400 44
#setxkbmap -option caps:escape

# load wal colors
# wal -R

bspc config border_width        2
bspc config window_gap          20

# Set the border colors.
bspc config normal_border_color "#08090b"
bspc config active_border_color "#08090b"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#08090b"

bspc config bottom_padding -5
bspc config top_padding 25
bspc config left_padding -5
bspc config right_padding -5

bspc config split_ratio          0.50
bspc config gapless_monocle      false
bspc config click_to_focus        true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config external_rules_command $HOME/.config/bspwm/external_rules

bspc rule -a "feh" state=floating
bspc rule -a "Zathura" state=floating
# bspc rule -a "xwinwrap" state=floating
# bspc rule -a "net-runelite-launcher-Launcher" state=floating
# bspc rule -a "xfce4-panel" layer=above
# bspc rule -a "gifview" state=floating
# bspc rule -a "TelegramDesktop" state=pseudo_tiled
bspc rule -a "Skype" focus=off

# titlebar script
# /home/me/.scripts/title.sh &
